#!~/.local/bin/node
authorName: default
experimentName: xgb
trialConcurrency: 5
maxExecDuration: 12h
maxTrialNum: 50
#choice: local, remote
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
logDir: ./xgboost_trials 
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE 
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 0
